### ISSUE TITLE
Question on code

### ISSUE THREAD

**Issue by nguyenvanthan** [pinterest/secor#107]
Hi,

I saw a strange line here: 
https://github.com/pinterest/secor/blob/master/src/main/java/com/pinterest/secor/parser/OffsetMessageParser.java#L36

What is the expected behavior ?
It seems to do useless operation ...

**Comment by pgarbacki** [comment]
(19 / 10) * 10 = 10

**Comment by nguyenvanthan** [comment]
@pgarbacki ok it's because the operand is integral.
It's a little weird thing of java language :smile: 
It's effectively different than : ((float) 19 / 10) * 10
Thank you for your answer. 

And i have another question for this line :
https://github.com/pinterest/secor/blob/master/src/main/java/com/pinterest/secor/consumer/Consumer.java#L85

Why do you limit this time to 10 minutes and why do you divide the value set by 2 ?

**Comment by pgarbacki** [comment]
It's a heuristic. We don't want to evaluate the upload policy too often because it is expensive but we also don't want to lag too much behind. In a typical case, the file-age-based upload policy is expressed in tens of minutes to prevent excessive fragmentation so setting the minimum at that level seemed sensible.
