### ISSUE TITLE
Manual S3 purge possibility

### ISSUE THREAD

**Issue by YakobovLior** [pinterest/secor#1336]
Hello,
is there a possibility to tell Secor to upload the data to S3 manually, instead of the configured values?
(200MB, 1 hour).
We need this feature since we are considering to run Secor on AWS Spot Instances, and in case the EC2 will be interrupted, the storage can be lost so uploading the current data to S3 can be helpful.

Thanks,
Lior

**Comment by HenryCaiHaiying** [comment]
Wasn't sure what the request is, do you want to upload the pending data
secor saved on the local disk before the node crash?  Can you just tune the
upload policy (on time or file size) to upload more frequent to S3?  Even
if the node crashes with the unloaded data, nothing is really lost since
the data is still in the Kafka queue and secor will pick up those data
again from Kafka when the node restarted.

**Comment by YakobovLior** [comment]
Hey @HenryCaiHaiying ,
I can configure Secor to upload more frequently, lets say that I'm uploading every 5 minutes instead of 1 hour.
I know that if the node will restart it will continue to pull from Kafka from where it stopped, but in my case if the node has crashed, it's storage is deleted, so it can cause that data which was read from Kafka and stored on the disk, was not uploaded to S3.
This is why I asked, if there is a possibility to make Secor upload data to S3 at a specific point of time.

Thanks,
Lior

**Comment by HenryCaiHaiying** [comment]
There is no data loss even in that situation.  Secor will re-pull from
Kafka from the last committed offset point on node restart and the
committed offset is only updated when secor is able to upload to S3
successfully.  The committed offset was used to store in ZK node and I
think it can also be configured to save in Kafka's __consumer_offsets topic
