### ISSUE TITLE
Secor v0.29 is released

### ISSUE THREAD

**Issue by HenryCaiHaiying** [pinterest/secor#1464]
Checkout the release notes: https://github.com/pinterest/secor/blob/master/RELEASE.md

v0.29
Javadoc Update: fix a few missing params and exclude a few packages
Add native support for Prometheus
Rework cleanup process on shutdown
Add secor.max.active.files property to controll active file count
Add max.poll.interval.ms kafka producer setting
Fix various unit test failures related to powermock running in JDK 11
Upgrade guava to 24.1.1 to address the following security issue
Upgrade parquet version from 1.9.0 to 1.11.0

**Comment by dovka** [comment]
Henry,
I  compiled and installed v0.29 but can't make it work.
I upgrade from v0.26 and afraid that configuration changed significantly so I ended up with config that doesn't work.

here is my run command:

java -ea -Dsecor.kafka.group=secor_backup -Xmx1194m -Daws.access.key=ZZZZZZZZZZZZZZ -Daws.secret.key=ZZZZZZZZZZZZZZZZZ -Daws.region=us-east-1 -Dzookeeper.quorum=0.zk.service.consul:2181,1.zk.service.consul:2181,2.zk.service.consul:2181 -Dkafka.zookeeper.path=/ -Dkafka.seed.broker.host=kafka.service.consul -Dkafka.seed.broker.port=9092 -Dsecor.s3.bucket=mobileye.secor.intermediate -Dsecor.s3.filesystem=s3n -Dsecor.s3.path=jenkins0 -Dsecor.kafka.topic_filter= -Dsecor.message.parser.class=com.pinterest.secor.parser.RsdParser -Dmessage.timestamp.name=@timestamp -Dsecor.local.path=/tmp/secor_data -Dsecor.file.reader.writer.factory=com.pinterest.secor.io.impl.DelimitedTextFileReaderWriterFactory -Dsecor.compression.codec= -Dsecor.max.file.age.seconds=30 -Dsecor.max.file.size.bytes=50000 -Dostrich.port=19999 -Dsecor.kafka.topic_blacklist=secor.restore -Dsecor.upload.manager.class=com.pinterest.secor.uploader.S3UploadManager -Dlog4j.configuration=file:///opt/secor/log4j.prod.properties -Dconfig=secor.me.prod.backup.properties -cp secor.jar:lib/* com.pinterest.secor.main.ConsumerMain

the parameters are spread over many config files, it would be nice if secor would print them out at the startup like kafka...
any specific values you want to see or all?

The process is running but does nothing:
![image](https://user-images.githubusercontent.com/22493212/88288747-e1c79600-ccfc-11ea-8b45-84015083d097.png)


BTW, side issue - I could not start the process because of the error in OstrichAdminService,
until I put build.properties in com/pinterest/secor/common/monitoring/ directory.

2020-07-22 21:16:38,719 [main] (com.pinterest.secor.common.monitoring.OstrichAdminService:81) ERROR Failed to load properties from build.properties
java.lang.NullPointerException
        at com.pinterest.secor.common.monitoring.OstrichAdminService.start(OstrichAdminService.java:75)
        at com.pinterest.secor.main.ConsumerMain.main(ConsumerMain.java:69)

Not sure why it needs it and what is the correct way to fix the issue.
Looks completely unnecessary though.

Thanks for your help!
David

**Comment by HenryCaiHaiying** [comment]
For some reason, I couldn't reproduce your problem of build.properties, there is build.properties packaged already inside secor.jar, looks fine to me.

To debug your consumer problem, you can turn on DEBUG logging category in your log4j file.

Which version of kafka are you running?

**Comment by dovka** [comment]
Henry,
thank you for the quick answer.
We run kafka 2.5.0
Here is DEBUG-enabled log for the first 6 minutes of the service startup.
[secor-debug.log](https://github.com/pinterest/secor/files/4969650/secor-debug.log)
I looked thorough but don't see any obvious (it is a lot of debug prints :) )
Appreciate your help!
David

**Comment by HenryCaiHaiying** [comment]
It seems you are not subscribing to any topics: -Dsecor.kafka.topic_filter= 

You can also try to run a few jstack command to what each thread was doing.

**Comment by dovka** [comment]
Henry,
thanks a lot!
The behavior had changed form version 0.26.
we never set secor.kafka.topic_filter in prev versions.
We set secor.kafka.topic_blacklist=topic-to-exclude
which used to mean "all topics except topic-to-exclude"

Right now I had to set secor.kafka.topic_filter=.* to make it work.
Appreciate your help!
David

**Comment by tomaskoutny-blis** [comment]
Hi @HenryCaiHaiying, I've experienced the same issue with `build.properties` as @dovka did. In my secor.jar, the file is located in `com/pinterest/secor/common/` rather than `com/pinterest/secor/common/monitoring/` where the following piece of code expects it
https://github.com/pinterest/secor/blob/f9055b9d477fb14d2c7f9ab126477d094c0ca47a/src/main/java/com/pinterest/secor/common/monitoring/OstrichAdminService.java#L75

**Comment by HenryCaiHaiying** [comment]
Make a fix for this problem: https://github.com/pinterest/secor/pull/1528

**Comment by HenryCaiHaiying** [comment]
@tomaskoutny-blis
