### ISSUE TITLE
Secor is not committing offsets to Kafka

### ISSUE THREAD

**Issue by kishorenc** [pinterest/secor#230]
It seems like Secor is not committing the topic offsets into Kafka. So, when a process gets restarted, the messages are streamed from the start, and old messages are being filtered in the client code. This seems very inefficient. 

I saw a similar question on the [mailing list](https://groups.google.com/forum/#!topic/secor-users/V1C64zJzs_w). It would be great if someone can explain this behavior. 

cc @HenryCaiHaiying

**Comment by HenryCaiHaiying** [comment]
By default, Secor is using the ZK to store the committed offsets, which is
actually easier to monitor comparing to storing the offset in kafka.

Did you configure it to store offsets in ZK or Kafka broker?

**Comment by kishorenc** [comment]
What I'm looking for is to have Secor rely on Kafka's offset commit mechanism instead of using a custom ZK storage. Is to correct to say that with the current implementation, Secor does not ever commit the consumer offset to Kafka using the Kafka consumer client, and instead relies on it's own offset management based on ZK? 

There are 2 reasons for my question/request:

1. We use a Kafka offset monitoring tool that tracks the offsets of various consumer, but Secor's backup consumer never shows up there. If it did, it would help us track lags using an existing tool instead of using the `Progress monitor` that's bundled with Secor.

2. As I mentioned earlier, when a Secor process gets restarted, the messages are streamed from the start (i.e. the first message in the partition) and old messages are dropped in the client code by comparing the offset with last committed offset from ZK. This seems inefficient. If the consumer offsets were committed into Kafka, the stream will resume automatically from the last committed offset.

**Comment by HenryCaiHaiying** [comment]
Looks like you have configuration issue, secor does commit's the offset
into ZK.  Take a look at secor.zookeeper.path to see where it's pointing
to, and use ZK client shell to check whether the offset is written to ZK.

**Comment by kishorenc** [comment]
My bad - I just realized that Secor is storing offsets in the same ZK path as the Kafka consumer code. I was misled because I was trying to find a `consumer.commit()` in the code. 

Is it possible to get Secor to commit the offsets into a Kafka topic instead of Zookeeper? This is because the Kaka documentation says that the Zookeeper based offset storage mechanism [will be deprecated soon](http://kafka.apache.org/documentation.html#impl_zkconsumers).

**Comment by HenryCaiHaiying** [comment]
We actually had played with the that __consumer_offsets topic for storing
the offset, it was not easy to use.  In order to find the latest offset,
you need to scan through all the messages in the queue to dedup and figure
out the latest value, similarly when you need to manually set the offset to
a certain value (or just clear/reset the offset), you will need to write a
small problem to do the publishing.

ZK is just so much easier to use, there is the simple command line client
shipped with ZK, or there is many ZK GUI tool for you to monitor or modify
the ZK path.

I think we will be keep using ZK until the __consumer_offsets based tool is
catching up.

The real reason for kafka to use broker offsets is ZK has scalability
issues on dealing with large number of partitions all at once.  But most of
customers don't have thousand partition topic, I don't think it will be an
imminent performance problem for most of us.

**Comment by kishorenc** [comment]
Thanks for the explanation. That makes sense. I'm closing this issue for now.

**Comment by dwo** [comment]
@HenryCaiHaiying Is there any interesting reason for not using `consumer.commit()`? It seems like Secor implements some code which the Kafka client can do for you? 

We're another use-case that would like to move to Kafka `__consumer_offsets` if possible, just because we have some better internal tooling around tracking that topic. We could extend our internal tooling to cover Zookeeper offsets too, but Secor is the only thing still using it here.

**Comment by HenryCaiHaiying** [comment]
I think technically it's possible to switch to use consumer.commit(), if you got some bandwidth you are certainly welcome to make a contribution for that code change.
