### ISSUE TITLE
Failed to apply upload policy when s3a is used.

### ISSUE THREAD

**Issue by oche191** [pinterest/secor#232]
Hello. I've already found couple of similar issues like that e.g https://github.com/pinterest/secor/issues/160

When i am trying to use s3a to write to some bucket located in eu-central or eu-west i am always getting following error:

> `java.lang.RuntimeException: Failed to apply upload policy
>   at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:116)
>   at com.pinterest.secor.consumer.Consumer.run(Consumer.java:106)
> 
> Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManager.<init>(Lcom/amazonaws/services/s3/AmazonS3;Ljava/util/concurrent/ThreadPoolExecutor;)V
>   at java.util.concurrent.FutureTask.report(FutureTask.java:122)
>   at java.util.concurrent.FutureTask.get(FutureTask.java:192)
>   at com.pinterest.secor.uploader.FutureHandle.get(FutureHandle.java:34)
>   at com.pinterest.secor.uploader.Uploader.uploadFiles(Uploader.java:104)
>   at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:196)
>   at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:228)
>   at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:114)
>   ... 1 more
> 
> Caused by: java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManager.<init>(Lcom/amazonaws/services/s3/AmazonS3;Ljava/util/concurrent/ThreadPoolExecutor;)V
>   at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:287)
>   at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653)
>   at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
>   at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
>   at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
>   at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
>   at com.pinterest.secor.util.FileUtil.getFileSystem(FileUtil.java:87)
>   at com.pinterest.secor.util.FileUtil.moveToCloud(FileUtil.java:206)
>   at com.pinterest.secor.uploader.HadoopS3UploadManager$1.run(HadoopS3UploadManager.java:66)
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)`

I've found couple of answers regarding this in internet and they are all about class clash between aws-java-sdk and the same lib from hadoop-aws artifact. 
I've tried current set up and also updated a aws-java-sdk-s3, aws-java-sdk-sts to 1.11.19 and hadoop-common, hadoop-aws to 2.7.2 version.
Error remains the same. Of course i have aws-java-sdk excluded from hadoop-aws. + I've checked maven dependency tree and found no lib duplicates.

Regarding https://issues.apache.org/jira/browse/HADOOP-12420, there may be no cure for this until hadoop 2.8.0 release.

Could you suggest something ? Probably i am doing something wrong.
If you think that this issue is not relevant comment it and close, please.

Thank you.

**Comment by HenryCaiHaiying** [comment]
We haven't seen this type of errors in our env (we are using regular s3 and
s3n), can you try play with the jar by removing some jars in the lib/
folder to see if you can find the right set of jars?

If you can figure out the runtime jars, we can always modify the pom.xml to
adjust for the runtime setup.

**Comment by llamahunter** [comment]
I see this too.

```
2016-07-28 03:49:36,768 [Thread-9] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-9,5,main] failed
java.lang.RuntimeException: Failed to apply upload policy
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:116)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:106)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManager.<init>(Lcom/amazonaws/services/s3/AmazonS3;Ljava/util/concurrent/ThreadPoolExecutor;)V
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.pinterest.secor.uploader.FutureHandle.get(FutureHandle.java:34)
        at com.pinterest.secor.uploader.Uploader.uploadFiles(Uploader.java:104)
        at com.pinterest.secor.uploader.Uploader.checkTopicPartition(Uploader.java:195)
        at com.pinterest.secor.uploader.Uploader.applyPolicy(Uploader.java:227)
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:114)
        ... 1 more
Caused by: java.lang.NoSuchMethodError: com.amazonaws.services.s3.transfer.TransferManager.<init>(Lcom/amazonaws/services/s3/AmazonS3;Ljava/util/concurrent/ThreadPoolExecutor;)V
        at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:287)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
        at com.pinterest.secor.util.FileUtil.getFileSystem(FileUtil.java:87)
        at com.pinterest.secor.util.FileUtil.moveToCloud(FileUtil.java:206)
        at com.pinterest.secor.uploader.HadoopS3UploadManager$1.run(HadoopS3UploadManager.java:66)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

I'm just using the stock secor tarball from maven central with the s3a upload policy.

**Comment by HenryCaiHaiying** [comment]
Are you able to do some debugging by replacing or removing some jars from
lib/?

**Comment by ache191** [comment]
Hello Henry,

Excuse me for a long delay. I've got this issue fixed. It will not work if we will replace/remove jars. The problem is a bit deeper in `hadoop-aws jar` itself and can not be reproduced wit s3 or s3n filesystems. 

First of all i've updated `aws-java-sdk-s3` and `aws-java-sdk-sts` to `1.11.19` versions. `hadoop-common` and `hadoop-aws `to `2.7.2` . This did not help. Than i've downloaded `hadoop 2.7.2` sources and build `hadoop-aws jar` against `aws-java-sdk 1.11.22` .  Then i've replaced original `hadoop-aws` in `secor/lib` dir and it started working with s3a filesystem and eu-central-1 region. Of course i am pretty sure that i've broke something, more deep testing is required. 

Seems we need to wait until next hadoop libs release.

**Comment by HenryCaiHaiying** [comment]
Oleksandr,

Thanks for digging deep into this problem.  From maven central, I saw
aws-java-sdk-sts version 1.11.22 was published as of 7/28, is that possible
that we can use use that version instead of building hadoop source code?

**Comment by ache191** [comment]
Henry,

I think this will not be possible, as we have a problem in Hadoop itself. I think hadoop release 2.8 should fix this situation.

**Comment by joshua-rutherford** [comment]
I ran into this today and since hadoop has cut `3.0.0-alpha1` I rebuilt secor with that dependency and `aws-java-sdk-*:1.10.6` (to match the dependency from hadoop) and s3a appears to work for me now.  Not sure what this breaks elsewhere.

**Comment by regispl** [comment]
I'm having the same problem and can't figure out how to make Secor work. I've rebuilt Secor with Hadoop 3.0.0-alpha1 and AWS SDK 1.10.6 as @joshua-rutherford suggested (it compiles fine, passes tests etc.) and set `secor.s3.filesystem` to `s3a` and `aws.region` to `eu-central-1`, but it wasn't enough because of the `org.apache.hadoop.fs.s3a.AWSS3IOException: doesBucketExist` exception in client.

Based on suggestions in https://issues.apache.org/jira/browse/HADOOP-13324 and http://hadoop.apache.org/docs/current3/hadoop-aws/tools/hadoop-aws/index.html I've set `fs.s3a.endpoint` to `s3.eu-central-1.amazonaws.com` by passing extra `-D` property when starting Secor, but it's still not working - I'm getting the same error. Is this possible that this property doesn't get overriden? Are there any other settings I should set?

Did anyone make Secor work with S3A in eu-central-1?

**Comment by msperlich** [comment]
From what I understand if you want to use "s3a" with the `HadoopS3UploadManager,` you'll get this error, because hadoop 2.72 is built against aws-java-sdk 1.7.4, whereas Secoe bundles a newer, incompatible version. One option is to downgrade the aws-java-sdk depdency in pom.xml to 1.7.4.

Unfortunately the `S3UploadManager` will stop compiling, since it requries the newer aws-java-sdk api. So at that point you  might be able delete `S3UploadManager`  and try compiling again.

What I ended up doing is just using `S3UploadManager` instead of `HadoopS3UploadManager` by setting  the `secor.upload.manager.class` property. This allows Secor to use IAM based authentication, which in my mind was the biggest advantage of "s3a" anyway.

**Comment by regispl** [comment]
Thanks @msperlich, this solved my problem - I wasn't aware that there's other uploader available. No deps update required, just switched to `S3UploadManager` and it worked 👍
