### ISSUE TITLE
Max no. of  threads / processes / partitions ?

### ISSUE THREAD

**Issue by RainbowTraveller** [pinterest/secor#247]
Is there any limit / cap to
- No. of threads in a secor process
- How many secor processes can be run in parallel (same machine or as a cluster on different machines)
- Max. no. of partitions per topic that can be handled by a secor cluster

Are there any MAX numbers that were tried successfully in above context.

I am trying following things
1. 6 secor processes (2 + 4 on Two separate machines with same consumer group and associated with same zookeeper cluster)
2. 10 threads per process
3. topic : logs having 60 partitions

It is invariably failing to sustain continuous processing. A scaled down setup with less traffic and less number of partitions works seamless.

**Comment by HenryCaiHaiying** [comment]
There will be a cap on max # of threads or processes since too many threads
or processes will causing too much OS scheduling overhead and CPU/Memory
threshing, but we have been using 100 threads/processes before.  Your
number 6 processes + 10 threads wouldn't cause problems.  You can monitor
CPU/Memory on the host to see if the usage is plateaued, most often the
performance is constrained by the box's I/O throughput.

In terms of number of partitions per topic, we have topic with 240
partitions without much problem.
