### ISSUE TITLE
How to monitor logs in statsd server - Secor

### ISSUE THREAD

**Issue by sriman** [pinterest/secor#320]
We have configured statsd hostport by

statsd.hostport=127.0.0.1:8010

I am running statsd in 127.0.0.1(host) and in port 8010, Can't see the log in the statsd, Am i missed anything

Can anyone help me by suggesting step by step implementation for monitoring using statsd

**Comment by mlabardini** [comment]
I’m having the same issue.   Are there any suggestions?

**Comment by trevorr** [comment]
Works for me. You probably also need to set `monitoring.interval.seconds`, as the default of 0 will just cause the monitor to run once and terminate. Be sure to set `secor.kafka.topic_filter` to something as well (such as `.*`), since leaving it blank doesn't seem to work. The logic around filters in the monitor seems to be a little different than secor itself, so I needed to use a separate configuration file for it. Finally, be sure to set properties before any use of `include`, as only the first occurrence of a setting is used.
