### ISSUE TITLE
Using KafkaConsumer in Secor

### ISSUE THREAD

**Issue by neoeahit** [pinterest/secor#341]
Hi,

Are there any plans to use the new KafkaConsumer provided with kafka 0.10.x instead of the [SimpleConsumer](https://github.com/pinterest/secor/blob/master/src/main/java/com/pinterest/secor/common/KafkaClient.java#L31) currently being used?

**Comment by HenryCaiHaiying** [comment]
Secor is actually using the high-level consumer for its main ingestion
logic.  The SimpleConsumer is only used in monitoring portion to monitor
the offset lag.

**Comment by neoeahit** [comment]
@HenryCaiHaiying Henry, we have seen issues with rebalancing, and hence wanted to move to the new KafkaConsumer. I see high level consumer is deprecated in the new version, and the new[Kafka Consumer] (https://github.com/apache/kafka/blob/0.10.2.1/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L508) uses kafka storage/coordination, which overall helps reducing the load on zookeeper. Hence we are eager and excited to move to the new KafkaConsumer.

Do you think this might be on the roadmap?

**Comment by HenryCaiHaiying** [comment]
Based on our experience, the unbalancing is usually caused by the load on
one particular consumer node, either because of GC or some other overhead.
Zookeeper usually is not a problem unless you have really big number of
partitions (in the order of 1000).

Given that we are already moving to a newer version of secor (merced)
internally, we would not intend to do any big changes to secor.  But we
welcome community to take on this endeavor of trying the new consumer.  The
new consumer programming model is a little bit easier to program than high
level consumer and it has some new API for you to rewind or subscribe to
one partition.  I don't think performance wise it would give you too much
boost though.

**Comment by neoeahit** [comment]
@HenryCaiHaiying Thanks for the quick update.
I have a three followup questions, 

1. Are there plans to open-source merced in near future? 
2. Is secor going to be deprecated in favor of merced?
2. Would it be possible to know more about how merced is different from secor( I was reading [ Pinterest Medium Article](https://medium.com/@Pinterest_Engineering/scalable-and-reliable-data-ingestion-at-pinterest-b921c2ee8754) (incase there is a plan to open-source it), it would be really helpful.

Thanks once again!

**Comment by HenryCaiHaiying** [comment]
Thanks for faithfully following the pinterest development.  We have plans
to open source merced but it was always de-prioritized.  In merced, we used
the low-level simple consumer and wrote our own work dispatcher to get
precise control.  And it's based on multi-tenant model to host all topics
in the same cluster (vs. secor, we deployed many clusters).

**Comment by neoeahit** [comment]
Thanks so much for the update!
