### ISSUE TITLE
[Q]: Behaviour for delayed messages w/ time-based partitioning

### ISSUE THREAD

**Issue by kujon** [pinterest/secor#350]
Hi,

I'm wondering what is Secor's behaviour for delayed messages when time partitioning is used. Let's say I partition daily and have got `partitioner.finalizer.delay.seconds` set to the default 3600. What happens to the messages for that day that arrived more than 1 hour after the end of the day?

Cheers

**Comment by HenryCaiHaiying** [comment]
The late-arrival message would still be put in the correct date folder
(yesterday's folder).  The issue here is your downstream app probably
already processed yesterday's date files, thus would ignore this
late-arrival message.  This is a typical problem on late-arrival message,
there are some techniques handling this problem:

1. increase finalizer.delay.seconds if you have a consistent late-arrival
problems.
OR 2. Have your downstream app check both today's folder and yesterday's
folder, pick up any new files since the last time they processed it;
OR 3. Change the file partition scheme to have files ordered by ingestion
time and then event time;
