### ISSUE TITLE
Unable to run Secor with secured zookeeper using a digest ACL scheme

### ISSUE THREAD

**Issue by famuyiwad** [pinterest/secor#407]
We are unable to run secor with a zookeeper that enforces user/role based authentication with digest ACL scheme so that only authorized services can securely access and manage znodes.
Has anyone setup secor with a secured zookeeper before?
Is it possible to configure and change the parent node, `consumers`?

Going through the code, it appears that secor only works with open unsafe, world/anyone zookeeper ACL and can't be configured to work with digest ACL scheme.

Thanks in advance.

**Comment by HenryCaiHaiying** [comment]
This is an area probably most people don't have experience with.  I saw
people securing kafka, but not much with securing zookeeper.  Does your
company really need securing ZK since ZK only contains some metadata/offset
information, it doesn't really have any sensitive user data.  In any ways,
feel free to explore this path and contribute to secor is you found how to
fix the ZK SSL communication.

**Comment by forsberg** [comment]
In a Secure Kafka environment with authentication and authorization, using the out of the box authorizer implementation, all the authorization information (i.e what users are allowed to do what to what topics and consumer groups) are stored in Zookeeper.

Hence, ZK very much contains sensitive data, which at least need to be protected from modifications.

**Comment by HenryCaiHaiying** [comment]
Several options:

1. It that possible to have a security ZK cluster for kafka authorization
and a non-secure one for secor storing its offsets?
2. Putting in some code change to make secor use secure communication with
zookeeper
3. In the latest version of secor, I think secor can store its offsets in
kafka, maybe the dependency on ZK is not needed anymore.
