### ISSUE TITLE
How does secor handle partitions with a negative lag?

### ISSUE THREAD

**Issue by kchew534** [pinterest/secor#439]
Our kafka restarted last week due to running out of disk space. However, running kafka-consumer-offset-checker.sh showed all except one partition have a negative lag, furthermore, checking their offsets in zookeeper showed that they have not been updated since kafka restarted.

So how does secor handle this scenario? Or it is rather a kafka problem? I am trying to understand how all of this happened but don't have too much luck.

**Comment by HenryCaiHaiying** [comment]
Because secor is already ahead of kafka (because of kafka running out of
disk space and reset).  You probably need to manually reset the secor
offset in zookeeper (to remove it) to make secor reread.

The files secor read earlier probably need to be thrown out manually
because kafka is regenerating a different set of data for the same kafka
offset.

**Comment by kchew534** [comment]
How to figure out the "correct" offsets to be used if manually resetting it in zk?
What would happened if I reset the offset to zero?

**Comment by HenryCaiHaiying** [comment]
By resetting I mean remove that offset in ZK and throw away the old
ingested S3 files, secor will reinitialize for that partition (either
listening from beginning or the tail of the queue depending on

kafka.consumer.auto.offset.reset parameter)
