### ISSUE TITLE
Messages can be uploaded multiple times to different files

### ISSUE THREAD

**Issue by glasser** [pinterest/secor#600]
I think there's a fundamental problem with the Secor upload algorithm that can lead to messages appearing multiple times in backups.

Let's say you have a consumer running on a single topic/partition, dividing up messages into hourly files.  The current committed offset is 11111111111111111111. The messages it finds span an hour break. It has created these two files:

```
y=2019/m=02/d=28/H=10/1_1_11111111111111111111.gz
y=2019/m=02/d=28/H=11/1_1_11111111111111111111.gz
```

It decides to upload, takes out the Zookeeper lock, uploads both files, but crashes before updating the Zookeeper committed offset. (In practice this could be "uploads the first few of a large number of files", especially if you're using something like SplitByFieldMessageParser that produces many files not just on hour boundaries.)

A new consumer takes over this topic/partition and starts writing messages locally. It will choose the same filenames for its files. But for whatever reason, this consumer decides it's time to upload faster than the previous iteration did, before it even gets to the second hour worth of messages. It uploads only this file:

```
y=2019/m=02/d=28/H=10/1_1_11111111111111111111.gz
```

It successfully updates the ZK offset to 11111111111111199999, and continues reading messages.  Now it creates these two files locally and uploads them:

```
y=2019/m=02/d=28/H=10/1_1_11111111111111199999.gz
y=2019/m=02/d=28/H=11/1_1_11111111111111199999.gz
```

Now these files all exist in storage:

```
y=2019/m=02/d=28/H=10/1_1_11111111111111111111.gz (overwritten by the second attempt)
y=2019/m=02/d=28/H=10/1_1_11111111111111199999.gz
y=2019/m=02/d=28/H=11/1_1_11111111111111111111.gz (uploaded by the first attempt)
y=2019/m=02/d=28/H=11/1_1_11111111111111199999.gz
```

But messages in the third file also appear in the fourth file!

I haven't tried making this happen in practice; this is based on reasoning about the code.

My assumption has been that once Secor has made it well past a timestamp range you can assume that every Kafka message has been uploaded exactly once, but this example seems to break that.

One thought for fixing this: Each topic/partition gets a "current upload" node, which is a list of files in storage. The upload logic (Uploader.uploadFiles) becomes:

- Take out lock
- Read current offset from ZK and stop if it doesn't match what we think it should be (no change from present)
- Read "current upload" file if it exists and delete all files named there from storage.
- Write "current upload" file with the list of files we're going to upload to storage.
- Upload files to storage.
- Transactionally update the offset in ZK and delete "current upload" file.
- (Also update local state like we do now.)
- Drop lock

Thoughts?

**Comment by glasser** [comment]
Another fix is to ensure that the upload policy is always deterministic. (I think this is what Kafka Connect S3/GCS does.)  So no wallclock-time policies and maybe no "size on disk after compression" policies.  Just things like "number of messages", "size of messages read", maybe "skew in Kafka timestamp from the first one read".

**Comment by glasser** [comment]
Hmm, yeah, I'm not feeling great about the "current upload" file solution either. That's because the ZooKeeper distributed lock isn't magic. And in fact, as https://github.com/twitter/commons/issues/5 once it gets the lock it never tells the app code if the lock is lost.

If a process' connection to ZK gets messy while it's uploading files to storage, it can lose the lock but still continue happily uploading files to storage.  It will presumably fail to do the ZK write at the end because of the failed connection (maybe?) but the new process can get the lock while the old one is still doing uploads, and so deleting the files might not be effective.  So yeah, determinism it is!

**Comment by HenryCaiHaiying** [comment]
One way to work around that problem is only using uploadPolicy purely based
on file size (uploader.checkTopicPartition()), not based on time passed.
This way even if the work was reassigned from worker 1 to worker 2.  Worker
2 will do the exact same upload as the work 1 did, thus overwriting the
files on S3/GCS generated by worker 1.

I think initially secor only has upload policy based on file size, later
people adding other time based upload policy which violates the original
deterministic assumption.

**Comment by HenryCaiHaiying** [comment]
Or modify the upload code a little bit:

1. check whether the upload was triggered by time based policy
2. If it is, check whether the number of files to be updated >= the number
of files on S3/GCS, if it is, continue upload/overwrite
3.       if not skip this upload and wait for the next upload cycle.

**Comment by HenryCaiHaiying** [comment]
This problem is also solvable when we persist secor's committed offset in ZK we also encode the associated partitions along with it.  So instead of just persisting 11111111 into ZK, we persist 11111111_d=28/h=10_d=28/h=11 into the ZNode

**Comment by HenryCaiHaiying** [comment]
Actually the approach of encoding file names in ZK offset node won't work because committing offset in ZK is the last step of upload.  So if the upload failed, that information (list of file names) are not persisted.

I will go back to @glasser 's first suggestion but modify it a little bit (persist the in-memory lastSeenOffset onto a new ZK node path: lastSeenOffsetPath and add step 1.1 and 1.2)

1. acquire ZK lock for the current topic/partition
--- new ---> 1.1 check whether the in-memory lastSeenOffset >= ZK's lastSeenOffset, if not skip the rest;
--- new ---> 1.2 persist the in-memory lastSeenOffset onto ZK lastSeenOffsetPath
2. upload a list of files for the current topic/partition
3. persist the current offset to ZK committedOffset path
4. release ZK lock

**Comment by HenryCaiHaiying** [comment]
See PR: https://github.com/pinterest/secor/pull/1351
